service: csharp-webapi-sample

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-1
  memorySize: 128
  timeout: 10  

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  API:
    handler: ReportAPI::ReportAPI.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY